## Numpy

Импортировать NumPy под именем np

In [102]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [103]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Создать вектор размера 10, заполненный единицами

In [104]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Создать вектор размера 10, заполненный числом 2.5

In [105]:
np.full(10, 2.5)

array([ 2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [106]:
v = np.zeros(10)
v[5] = 1
v

array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

Развернуть вектор (первый становится последним)

In [107]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [108]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [109]:
ar = np.array([1, 2, 0, 0, 4, 0])
np.where(ar != 0)

(array([0, 1, 4], dtype=int64),)

Создать 3x3 единичную матрицу

In [110]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Создать массив 3x3x3 со случайными значениями

In [111]:
np.random.random((3, 3, 3))

array([[[ 0.5460909 ,  0.8285274 ,  0.82201962],
        [ 0.25933115,  0.60546387,  0.64479297],
        [ 0.06475362,  0.19012495,  0.86608375]],

       [[ 0.65925112,  0.08210806,  0.09132831],
        [ 0.72143668,  0.54141489,  0.77149264],
        [ 0.75380994,  0.63912386,  0.52688223]],

       [[ 0.73683967,  0.05974402,  0.46683969],
        [ 0.87624832,  0.86350917,  0.1412411 ],
        [ 0.87170766,  0.46442352,  0.10326089]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [112]:
np.random.random(30).mean()

0.57213976177344583

Перемножить матрицы 5x3 и 3x2

In [113]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))
np.dot(a, b)

array([[ 1.23280785,  1.06525045],
       [ 0.84851493,  0.94848226],
       [ 0.57994493,  0.65735734],
       [ 0.5694601 ,  0.6436441 ],
       [ 1.3271085 ,  1.26920524]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [114]:
ar = np.arange(1 / 11, 11 / 11, 1.0 / 11)
ar

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

Заменить максимальный элемент на ноль

In [115]:
ar[np.argsort(ar)[-1]] = 0.0
ar

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.        ])

Преобразовать массив из float в int

In [116]:
ar.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [117]:
from scipy.spatial import distance
coords = np.array([(1, 2), (1, 0), (3, 4), (5, 0), (7, 3), (1, 3), (8, 0), (3, 2), (6, 6), (5, 4)])
distance.cdist(coords, coords)

array([[ 0.        ,  2.        ,  2.82842712,  4.47213595,  6.08276253,
         1.        ,  7.28010989,  2.        ,  6.40312424,  4.47213595],
       [ 2.        ,  0.        ,  4.47213595,  4.        ,  6.70820393,
         3.        ,  7.        ,  2.82842712,  7.81024968,  5.65685425],
       [ 2.82842712,  4.47213595,  0.        ,  4.47213595,  4.12310563,
         2.23606798,  6.40312424,  2.        ,  3.60555128,  2.        ],
       [ 4.47213595,  4.        ,  4.47213595,  0.        ,  3.60555128,
         5.        ,  3.        ,  2.82842712,  6.08276253,  4.        ],
       [ 6.08276253,  6.70820393,  4.12310563,  3.60555128,  0.        ,
         6.        ,  3.16227766,  4.12310563,  3.16227766,  2.23606798],
       [ 1.        ,  3.        ,  2.23606798,  5.        ,  6.        ,
         0.        ,  7.61577311,  2.23606798,  5.83095189,  4.12310563],
       [ 7.28010989,  7.        ,  6.40312424,  3.        ,  3.16227766,
         7.61577311,  0.        ,  5.38516481

Случайно расположить p элементов в 2D массив

In [118]:
p = 20
size = 6
ar = np.zeros((size, size))
np.put(ar, np.random.choice(range(size * size), p, replace = False), 1)
ar

array([[ 0.,  1.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  1.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [119]:
ar = np.array([1, 2, 3, 4, 5])
np.insert(ar, np.repeat(np.arange(1, len(ar)), 3), 0)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

Найти наиболее частое значение в массиве

In [120]:
ar = np.array([1, 0, 2, 1, 1, 0])
u, counts = np.unique(ar, return_counts=True)
u[np.argmax(counts)]

1

Найти n наибольших значений в массиве

In [121]:
ar = np.array([5, 3, 6, 4, 1, 2])
n = 3
np.sort(ar)[-n:]

array([4, 5, 6])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [122]:
import pandas as pd
food = pd.read_table('en.openfoodfacts.org.products.tsv')

C:\Python35\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [123]:
food.head()

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [124]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [125]:
food.shape[1]

163

Напечатайте все названия столбцов

In [126]:
for column in food.columns:
    print (column)

code
url
creator
created_t
created_datetime
last_modified_t
last_modified_datetime
product_name
generic_name
quantity
packaging
packaging_tags
brands
brands_tags
categories
categories_tags
categories_en
origins
origins_tags
manufacturing_places
manufacturing_places_tags
labels
labels_tags
labels_en
emb_codes
emb_codes_tags
first_packaging_code_geo
cities
cities_tags
purchase_places
stores
countries
countries_tags
countries_en
ingredients_text
allergens
allergens_en
traces
traces_tags
traces_en
serving_size
no_nutriments
additives_n
additives
additives_tags
additives_en
ingredients_from_palm_oil_n
ingredients_from_palm_oil
ingredients_from_palm_oil_tags
ingredients_that_may_be_from_palm_oil_n
ingredients_that_may_be_from_palm_oil
ingredients_that_may_be_from_palm_oil_tags
nutrition_grade_uk
nutrition_grade_fr
pnns_groups_1
pnns_groups_2
states
states_tags
states_en
main_category
main_category_en
image_url
image_small_url
energy_100g
energy-from-fat_100g
fat_100g
saturated-fat_100g
-buty

Какое название у 105 столбца?

In [127]:
food.columns[105]

'-fructose_100g'

Какой тип наблюдений в 105 столбце?

In [128]:
food.dtypes[105]

dtype('float64')

Как проиндексирован набор данных?

In [129]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [130]:
food.at[19, 'product_name']

'Organic Oat Groats'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [131]:
chipo = pd.read_table('chipotle.tsv')

Как много продуктов стоят более чем $10.00?

In [138]:
chipo['item_price'] = (chipo['item_price'].replace( '[\$,)]','', regex=True )
                   .replace( '[(]','-',   regex=True ).astype(float))
chipo.loc[chipo['item_price'] / chipo['quantity'] > 10].shape[0]

1034

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [145]:
chipo[['item_name', 'item_price']]

item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
9                             Steak Burrito        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
13                             Chicken Bowl       11.25
14                      Chips and Guacamole        4.45
15    Chips and Tomatillo-Green Chili Salsa        2.39
16                          Chicken Burrito        8.49
17                          Chicken Burrito        8.49
18                              Canned Soda        2.18
19                             Chicken Bowl        8.75
20                      Chips and Guacamole        4.45
21                         Barbacoa Burrito        8.99
22                         Nantucket Nectar        3.39
23                          Chicken Burrito       10.98
24                                     Izze        3.39
25             Chips and Fresh Tomato Salsa        2.39
26                             Chicken Bowl        8.49
27                         Carnitas Burrito        8.99
28                              Canned Soda        1.09
29                          Chicken Burrito        8.49
...                                     ...         ...
4592                       Barbacoa Burrito       11.75
4593                          Carnitas Bowl       11.75
4594                          Barbacoa Bowl       11.75
4595                           Chicken Bowl        8.75
4596                    Chips and Guacamole        4.45
4597                      Canned Soft Drink        1.25
4598                          Bottled Water        1.50
4599                           Chicken Bowl        8.75
4600                    Chips and Guacamole        4.45
4601                      Canned Soft Drink        1.25
4602                       Barbacoa Burrito        9.25
4603                       Barbacoa Burrito        9.25
4604                           Chicken Bowl        8.75
4605                    Chips and Guacamole        4.45
4606                      Canned Soft Drink        1.25
4607                          Steak Burrito       11.75
4608                         Veggie Burrito       11.25
4609                      Canned Soft Drink        1.25
4610                          Steak Burrito       11.75
4611                         Veggie Burrito       11.25
4612                          Carnitas Bowl        9.25
4613                                  Chips        2.15
4614                          Bottled Water        1.50
4615                     Chicken Soft Tacos        8.75
4616                    Chips and Guacamole        4.45
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [134]:
chipo[['item_name', 'item_price']].sort_values('item_name')

item_name  item_price
3389  6 Pack Soft Drink       12.98
341   6 Pack Soft Drink        6.49
1849  6 Pack Soft Drink        6.49
1860  6 Pack Soft Drink        6.49
2713  6 Pack Soft Drink        6.49
3422  6 Pack Soft Drink        6.49
553   6 Pack Soft Drink        6.49
1916  6 Pack Soft Drink        6.49
1922  6 Pack Soft Drink        6.49
1937  6 Pack Soft Drink        6.49
3836  6 Pack Soft Drink        6.49
298   6 Pack Soft Drink        6.49
1976  6 Pack Soft Drink        6.49
1167  6 Pack Soft Drink        6.49
3875  6 Pack Soft Drink        6.49
1124  6 Pack Soft Drink        6.49
3886  6 Pack Soft Drink        6.49
2108  6 Pack Soft Drink        6.49
3010  6 Pack Soft Drink        6.49
4535  6 Pack Soft Drink        6.49
4169  6 Pack Soft Drink        6.49
4174  6 Pack Soft Drink        6.49
4527  6 Pack Soft Drink        6.49
4522  6 Pack Soft Drink        6.49
3806  6 Pack Soft Drink        6.49
2389  6 Pack Soft Drink        6.49
3132  6 Pack Soft Drink        6.49
3141  6 Pack Soft Drink        6.49
639   6 Pack Soft Drink        6.49
1026  6 Pack Soft Drink        6.49
...                 ...         ...
2996       Veggie Salad        8.49
3163       Veggie Salad        8.49
4084       Veggie Salad        8.49
1694       Veggie Salad        8.49
2756       Veggie Salad        8.49
4201  Veggie Salad Bowl       11.25
1884  Veggie Salad Bowl       11.25
455   Veggie Salad Bowl       11.25
3223  Veggie Salad Bowl       11.25
2223  Veggie Salad Bowl        8.75
2269  Veggie Salad Bowl        8.75
4541  Veggie Salad Bowl        8.75
3293  Veggie Salad Bowl        8.75
186   Veggie Salad Bowl       11.25
960   Veggie Salad Bowl        8.75
1316  Veggie Salad Bowl        8.75
2156  Veggie Salad Bowl       11.25
4261  Veggie Salad Bowl       11.25
295   Veggie Salad Bowl       11.25
4573  Veggie Salad Bowl        8.75
2683  Veggie Salad Bowl        8.75
496   Veggie Salad Bowl       11.25
4109  Veggie Salad Bowl       11.25
738   Veggie Soft Tacos       11.25
3889  Veggie Soft Tacos       16.98
2384  Veggie Soft Tacos        8.75
781   Veggie Soft Tacos        8.75
2851  Veggie Soft Tacos        8.49
1699  Veggie Soft Tacos       11.25
1395  Veggie Soft Tacos        8.49

[4622 rows x 2 columns]

Сколько было заказано самого дорогого предмета?

In [143]:
chipo.iloc[np.argsort(chipo.item_price / chipo.quantity).values].tail(1)['quantity'].tolist()[0]

1

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [136]:
chipo.loc[chipo['item_name'] == 'Veggie Salad Bowl'].shape[0]

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [137]:
chipo.loc[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].shape[0]

20